# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Keith R. Bennett's Technical Blog"
name:  "Keith R. Bennett's Technical Blog"

email: keithrbennett@gmail.com

url: "http://keithrbennett.github.io" # the base hostname & protocol for your site, e.g. http://example.com

description: Technical Explorations

description: >- # this means to ignore newlines until "baseurl:"
  Technical Explorations
baseurl: "/blog" # the subpath of your site, e.g. /blog
twitter_username: keithrbennett
github_username:  keithrbennett

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea/


#Fix suggested at https://github.com/github/pages-gem/issues/399 for error:
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
github: [metadata]
